Initial setup
security-summer-school/essentials pull request #1
Opened 2021-08-13 13:04 UTC by teodutu

Prepare the repo for content development.

2021-08-13 20:57 UTC, gabrielmocanu approved these changes
I don't see any issue. I think it's good to go.

2021-08-14 11:41 UTC, razvand requested changes
I would merge the `Tutorials` and `Challenges` sections in a single `Activities` section. Because tutorials and challenges may be interleaved.

I suggest we use a blank line after every heading title. It makes it more clear to read / write Markdown.

2021-08-14 11:41 UTC, razvand commented on README.md
> +- TODO
Why not list sessions?

I would enumerate them using the [ordered list syntax for GitHub Markdown](https://guides.github.com/features/mastering-markdown/).

2021-08-14 12:11 UTC, teodutu commented on README.md
> +- TODO
I was leaving room for changes to the order of the sessions. But on second thought, the current ordering should not require modifications, so I'll just add it here.

2021-08-18 02:04 UTC, razvand approved these changes
I suggest we write one (entire) phrase per line to make nice diffs.

Other than that, it's all good on my side.

2021-08-18 19:14 UTC, razvand approved these changes
All good

2021-08-18 19:35 UTC, merged