Finish session "Explaining the Internet"
security-summer-school/essentials pull request #19
Opened 2022-06-25 20:55 UTC by teodutu

- [x] Finish session content
- [ ] Add challenges

2022-06-27 15:44 UTC, gabrielmocanu commented
Any reasons to drop information about Nmap on the Port section?

2022-06-27 15:50 UTC, gabrielmocanu requested changes

2022-06-27 15:50 UTC, gabrielmocanu commented on explaining-the-internet/index.md
> +Most moblile phones prefer the WiFi connection, but remain connected to 4G mobile data, which they use as backup.
```suggestion
Most mobile phones prefer the WiFi connection, but remain connected to 4G mobile data, which they use as backup. 
```

2022-06-27 15:50 UTC, gabrielmocanu commented on explaining-the-internet/index.md
> +Each network contains one **router** which sends data between the hosts in its network and those on other netowrks.
```suggestion
Each network contains one **router** which sends data between the hosts in its network and those on other networks.
```

2022-06-27 15:50 UTC, gabrielmocanu commented on explaining-the-internet/index.md
>  Sad reacts only.
I don't think this fits well here.
```suggestion
```

2022-06-27 15:50 UTC, gabrielmocanu commented on explaining-the-internet/index.md
> +Obviously, each of them serve the same web page: `security.summer.schoo.github.io`.
```suggestion
Obviously, each of them serves the same web page: `security.summer.schoo.github.io`.
```

2022-06-27 23:07 UTC, teodutu commented
> Any reasons to drop information about Nmap on the Port section?

Yes, `nmap` needs a discussion about network masks, which would take a very long time from an already very theoretically-heavy session. It kind of sucks now because it's left me without one challenge idea, but it might be for the better overall.

2022-06-28 04:48 UTC, teodutu commented on explaining-the-internet/index.md
>  Sad reacts only.
You're such a boomer. But _sometimes_ boomers are right.

2022-06-28 04:53 UTC, teodutu commented
>  Notice that only the domain of a URL gets DNS'd. -> I don't get it.. DNS'd ??

`get DNS'd` = have its name resolved to an IP address by the DNS

But I get it, I won't invent words anymore.

2022-06-28 05:17 UTC, teodutu commented
@gabrielmocanu I've added your suggestions. Please have another look. I discarded those with spelling suggestions such as:
- `*ise` -> `*ize`
- `favourite` -> `favorite`

All spelling are correct. I just prefer the former ones (British English) as opposed to the latter (American English).

In addition, do you have any ideas for another 1 or 2 challenges?

2022-06-29 16:55 UTC, gabrielmocanu commented
Use john to brute-force password when login in with ssh.

2022-06-30 13:36 UTC, merged