Add `Application Lifetime` session content
security-summer-school/essentials pull request #25
Opened 2022-07-16 10:42 UTC by cristian-vijelie

2022-07-16 14:46 UTC, teodutu requested changes
The content is fine technically apart from some inconsistencies. However, this is more of a heavily shrunk OS class rather than a session on Application Lifetime. It would be better with more demos and preferably images. Take whatever you wish from our [new OS class](https://github.com/systems-cs-pub-ro/operating-systems-oer/pulls) or from the Internet. Also, some of the concepts are introduced very bluntly. Be more gentle, add some lube.

@razvand what do you say?

2022-07-16 14:46 UTC, teodutu commented on application-lifetime/index.md
> +#### Linking
Say a bit about object files before linking. Otherwise, it's unclear what you are linking precisely. Use `file` to show the difference and come back to this step in the session on "Assembly Language".

2022-07-16 14:46 UTC, teodutu commented on application-lifetime/index.md
> +##### PIE - Position Independent Executable
This is too sudden and probably unnecessary.

2022-07-16 14:46 UTC, teodutu commented on application-lifetime/index.md
> +Each process has at least one execution **thread**, that runs the code of the application, one **virtual address space**, and one **file descriptor table**.
You've just introduced 3 large and difficult topics in the same phrase: threads, VAS and fd table. Are they really necessary? I'd skip them.

2022-07-16 14:46 UTC, teodutu commented on application-lifetime/index.md
> +They represent abstractions of the main resources of the system: **CPU**, **memory**, **I/O**.
Simply saying that the OS provides abstractions of these resources together with some high-level reasons why they are needed should suffice.

2022-07-16 14:46 UTC, teodutu commented on application-lifetime/index.md
> +The **virtual memory** is the abstraction of the system's memory.
Start with a story that there are thousands of threads (do a demo with `ps -ef` or `htop`) and then introduce the need for an abstraction over the physical memory.

2022-07-16 14:46 UTC, teodutu commented on application-lifetime/index.md
> +- CODE - R-X - the code of the program
Say that is's compiled and, thus, in binary format, not the code written by the developer.

2022-07-16 14:46 UTC, teodutu commented on application-lifetime/index.md
> +Each section can have one or more of the following permissions: **read** (R), **write** (W), **execute** (X).
```suggestion
Each section can have one or more of the following permissions: **read (R)**, **write (W)**, **execute (X)**.
```

2022-07-16 14:46 UTC, teodutu commented on application-lifetime/index.md
> +- RODATA - R-- - the read-only global initialized variables
- Add a demo with a short C program that creates several variables and show where each of them resides
- Bold the names of the sections and their permissions.
- The heap and the stack are not rwx.

2022-07-16 14:46 UTC, teodutu commented on application-lifetime/index.md
> +They are, by default, both writable and executable.
They're not on any more recent version of GCC. Better remove this info or you might cause confusion.

2022-07-16 14:46 UTC, teodutu commented on application-lifetime/index.md
> +Shellcodes represent a big part of the SSS Binary track.
```suggestion
Shellcodes represent a [big part of the SSS Binary track](https://security-summer-school.github.io/binary/shellcodes/).
```

2022-07-16 15:11 UTC, cristian-vijelie commented
Demos and code snippets are to be added. It's not the final form, I'm not a murderer

2022-07-17 06:18 UTC, cristian-vijelie commented on application-lifetime/index.md
> +- RODATA - R-- - the read-only global initialized variables
they are, because by default NX is disabled

2022-07-17 11:19 UTC, cristian-vijelie commented on application-lifetime/index.md
> +Interpreted code isn't the focus of the session, but can be interesting for those that want to dwelve into Web Security - the browser is an interpretor of JavaScript code.
I'm simplyfing things.

2022-07-17 11:32 UTC, cristian-vijelie commented on application-lifetime/index.md
> +Interpreted code isn't the focus of the session, but can be interesting for those that want to dwelve into Web Security - the browser is an interpretor of JavaScript code.
At a high level, the browser is the interpreter. Yes, it has components that do the effective interpretation, but you can consider that the browser, as a whole, reads the code and acts according to it

2022-07-17 18:58 UTC, teodutu reviewed
I made a few more comments. On top of them, I really like the images.

2022-07-17 18:58 UTC, teodutu commented on application-lifetime/index.md
> +# Table of Contents
Remove this. We decided we won't be using it anymore.

2022-07-17 18:58 UTC, teodutu commented on application-lifetime/index.md
> +# Content Sections:
No need for this section. Simply start with `# From Code to Application`. This will increase the section level in the entire session (`##` -> `#` etc.).

2022-07-17 18:58 UTC, teodutu commented on application-lifetime/index.md
> +The **virtual memory** is the abstraction of the system's memory.
Now that I think of it, I don't believe that **Virtual** Memory is necessary. I think just sticking to "memory" and saying "address space" is enough.

2022-07-17 18:58 UTC, teodutu commented on application-lifetime/index.md
> +For example, if the parent wants to receive data from the child, it will close the in-end, and the child will close the out-end.
I think you went overboard with this. Why is this needed? Sticking to `fork` should be enough.

2022-07-17 18:58 UTC, teodutu commented on application-lifetime/index.md
> +## Creating a Process
See if the resources given by @razvand here [1] are useful to you. They might help you explain this section in a smoother way.

[1] https://github.com/systems-cs-pub-ro/operating-systems-oer/pull/5#discussion_r915513591

2022-07-18 06:29 UTC, razvand requested changes
All in all, a pretty good session. It is however too much, it's a packing of 4-5 OS lectures and 2-3 binary track sessions in one (static analysis, dynamic analysis, ELF). See my comments regarding trimming down content.

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +That code can be compiled or interpreted, in order to do what the user wants it to do.
```suggestion
That code can be compiled or interpreted, in order to do what the developer wants it to do.
```

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +Interpreted code isn't the focus of the session, but can be interesting for those that want to delve into Web Security - the browser can be seen as an interpreter of JavaScript code.
```suggestion
Interpreted code isn't the focus of the session, but can be interesting for those that want to delve into web security - the browser can be seen as an interpreter of JavaScript code.
```

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +This session we will focus mainly on compiled code.
```suggestion
In this session we will focus mainly on compiled code.
```

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +For compiled code to become a working application, 3 steps are needed: **compling**, **linking** and **loading**.
Mention. "Some languages, such as C/C++, may provide an initial optional step of **preprocessing**."

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +Compiling is the step in which a piece of code becomes binary data, readable by the CPU.
```suggestion
Compiling is the step in which a piece of code becomes binary data, readable by the CPU, also called **machine code**.
```

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +Those libraries can be standard libraries (libc), OS-specific libraries - the ones for system calls, or libraries written by the user.
```suggestion
Those libraries can be standard libraries (libc), OS-specific libraries - the ones for system calls, or libraries written by developers and 3rd parties.
```

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +Linking is the step in which libraries are added to our application.
Not only this. Linking is the step in which multiple object files (belonging to the application) together with libraries are tied together in a final executable.

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +The result of the linking step is an ELF file (Execulable and Linkable File).
```suggestion
The result of the linking step is an executable file.
The format of the executable file depends on the operating system that runs it.
Linux uses the ELF (*Execulable and Linkable Format*).
Windows uses the PE (*Portable Executable*) format.
macOS uses the Mach-O (*Mach Object*) format.
```

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +TODO: Tutorial - create a static library
I wouldn't focus on creating libraries. I would only focus on analyzing them and using them.

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +However, the staticly-linked executables aren't more portable - maybe the library uses something not present on the system.
```suggestion
However, the statically-linked executables aren't more portable - maybe the library uses something not present on the system.
```

They are more portable. If a static executable doesn't work, for sure a dynamic one won't work. But not the other way around.

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +TODO: Tutorial - Create a dynamic library
I wouldn't focus on this.

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +One defining trait of the dynamic libraries is that they must be **PIE - Position Independent Executables**.
```suggestion
One defining trait of the dynamic libraries is that they must be compiled as PIC (*Position Independent Code*) objects.
```

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +##### PIE - Position Independent Executable
I agree. Drop it.

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +One of them is **Return to libc**, which is discussed at the binary track of SSS.
```suggestion
One of them is the **return-to-libc** attack, which is discussed at the binary track of SSS.
```

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +During this process, the program code is placed in the OS memory, the dynamic libraries are found, and everything is executed by the OS.
This seems to give too much credit and ownership to the OS. It seems the OS is everywhere. I would rephrase it to tone down the role of the OS as a bootstrapper of the process then handling the ropes to the application.

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +They represent abstractions of the main resources of the system: **CPU**, **memory**, **I/O**.
Agree.

I would say that a process has a view of the memory that we call the **process address space** and ditch the word `virtual` altogether.

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +### Threads
ditch

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +The **virtual memory** is the abstraction of the system's memory.
What he said. Just use "Process Address Space". Avoid `virtual`.

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +The virtual address space isn't fixed during the execution of a program; it can be changed by the program itself, using `mmap` to create new entires, and `mprotect` to change the permissions.
everything from mmap to private mmap, memory mapped files goes away, it's too much

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +For example, if the parent wants to receive data from the child, it will close the in-end, and the child will close the out-end.
What he said. Just show a short description of fork.

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +For example, if the parent wants to receive data from the child, it will close the in-end, and the child will close the out-end.
Actually drop it all. It's too much for this session. It just creates a new process and that's it.

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +### Exec
Drop this, it's too much.

2022-07-18 06:29 UTC, razvand commented on application-lifetime/index.md
> +### Advanced: Shared Memory
Drop this, too much.

2022-07-18 08:37 UTC, cristian-vijelie commented on application-lifetime/index.md
> +However, the staticly-linked executables aren't more portable - maybe the library uses something not present on the system.
A dynamic one might work where a static one doesn't, when porting. Consider a libc that uses AVX or something. If the system where the binary is ported doesn't have AVX, the static one will crash, the dynamic one will work

2022-07-18 08:40 UTC, cristian-vijelie commented on application-lifetime/index.md
> +### Exec
`exec` I think should stay. At binary they are expected to know what exec does

2022-07-18 19:32 UTC, teodutu requested changes
I made another pass and some minor suggestions. It's still a hardcore session, but it's a good one. Life is hard.

Here are some more high-level suggestions:
- Use C-style comments, not C++. Begin each comment with a capital letter and end it with a dot (`.`).
- Add `.gitignore`s to each challenge to ignore the binaries.
- Remove `give-me-that-shell/src/shell.c`
- Move the contents of the `my-own-puts` directory to `my-own-puts/src`.

2022-07-18 19:32 UTC, teodutu commented on application-lifetime/activities/dynamic-linking/src/Makefile
> +CC = gcc
You can make a generic C makefile and include that instead of having duplicates in every makefile. Use these [1] for inspiration.

[1] https://github.com/systems-cs-pub-ro/operating-systems-oer/pull/6/files

2022-07-18 19:32 UTC, teodutu commented on application-lifetime/activities/file-basics/src/basics.c
> +}
```suggestion
}

```

2022-07-18 19:32 UTC, teodutu commented on application-lifetime/activities/file-basics/src/basics.c
> +	// open the file as read-write
```suggestion
	/* Open the file as read-write. */
```

2022-07-19 10:03 UTC, teodutu reviewed
I explained what I meant with the makefiles

2023-06-25 12:46 UTC, teodutu requested changes
I made a high-level pass. Address my comments below and then I'll make a more in-depth one.

- Add solutions for all challenges.
- Change all boxes in `.svg` files to have rounded corners.
- Do you intend to make all the source code public? If not, move the code for the challenges to the [internal repo](https://github.com/security-summer-school/essentials-internal) together with the deployment infrastructure and only add binaries and tutorials here.
- Consider intermingling the tutorials and challenges with the written explanations. While reading the lab, the text seemed incomplete without immediate practical examples.

2023-06-25 12:46 UTC, teodutu commented on application-lifetime/index.md
> +Interpreted code isn't the focus of the session, but can be interesting for those that want to delve into web security - the browser can be seen as an interpreter of JavaScript code.
```suggestion
Interpreted code isn't the focus of the session, but can be interesting for those that want to delve into web security - the browser can be seen as an interpreter for JavaScript code.
```

2023-06-25 12:46 UTC, teodutu commented on application-lifetime/index.md
> +In this session we will focus mainly on compiled code.
```suggestion

In this session, we will focus mainly on compiled code.
```

2023-06-25 12:46 UTC, teodutu commented on application-lifetime/index.md
> +Some languages, like C and C++, require an additional step before compiling, **preprocessing**.
Preprocessing is overrated. I wouldn't even consider it a separate step. It's not relevant to this section, so you can simply remove this line.

2023-06-25 12:46 UTC, teodutu commented on application-lifetime/assets/from_code_to_elf.svg
Rename this to `from_code_to_process.svg`

2023-06-25 12:46 UTC, teodutu commented on application-lifetime/demo/exec/main.c
> +
```suggestion
```

2023-06-25 12:46 UTC, teodutu commented on application-lifetime/index.md
> +The diagram from above represents the process during which some source code becomes a running application.
```suggestion
The diagram above represents the process through which some source code becomes a running application.
```

2023-06-25 12:46 UTC, teodutu commented on application-lifetime/index.md
> +The compilation process creates **object files**, which are used in linking.
This is too much information all of a sudden. Break it up and take it slowly:
1. Mention the compiler and then use it to create an object file.
2. Try to run it and explain why this fails.
- This is where this subsection ends
3. Link the object file and then run it successfully.

Wrap all of this in a tutorial (containing a flag) where students are just supposed to compile and run an application.

2023-06-25 12:46 UTC, teodutu commented on application-lifetime/index.md
> +macOS uses the Mach-O (*Mach Object*) format.
A lot of information, soon to be forgotten. It's not needed, so ditch it. It just bloats an already condensed text.

2023-07-12 11:59 UTC, cristian-vijelie commented on application-lifetime/index.md
> +Some languages, like C and C++, require an additional step before compiling, **preprocessing**.
I believe it's better to leave it there, just so the students hear the term

2023-07-12 12:02 UTC, cristian-vijelie commented on application-lifetime/index.md
> +macOS uses the Mach-O (*Mach Object*) format.
Again, I think it's better that the students hear of the terms, at least

2023-07-16 13:01 UTC, mariasfiraiala requested changes
Thanks @cristian-vijelie. You'll find the comments from me below.

2023-07-16 13:25 UTC, cristian-vijelie commented on application-lifetime/assets/process_layout.svg
I didn't want to go into threads and VAS

2023-07-16 13:42 UTC, mariasfiraiala commented on application-lifetime/assets/process_layout.svg
Right, but the session already mentions the layout of the process memory, so VAS should be fine, and from processes to threads it's just a small step...

2023-07-17 08:13 UTC, teodutu requested changes
I still think this session is too dense, but I might be underestimating the students. If @mariasfiraiala is OK with the depth of these explanations, then so am I. And anyway it may be good to experiment with some more intense sessions. Perhaps the students can take them. If this turns out to be too much, we should probably split this session into 2: one on binaries and the second one on processes.

2023-07-17 08:13 UTC, teodutu commented on application-lifetime/index.md
> +The process memory is split into sections, which can contain one or more pages.
This is the first time you introduce the notion of pages. You need to elaborate on it before mentioning `mprotect()` below.

2023-07-17 08:13 UTC, teodutu commented on application-lifetime/index.md
> +The process address space isn't fixed during the execution of a program; it can be changed by the program itself, using `mmap` to create new entries, and `mprotect` to change the permissions.
```suggestion
The process address space isn't fixed during the execution of a program; it can be changed by the program itself, using `mmap()` to create new entries, and `mprotect()` to change the permissions.
```
Similarly, all function names must be followed by `()` to be distinct from other symbols.

2023-07-17 08:24 UTC, teodutu reviewed
The challenges seem fine. It's good that there are many tutorials since this session is quite demanding.

2023-07-17 08:24 UTC, teodutu commented on application-lifetime/index.md
> +We consider the case when we are in a terminal (bash) and we launch an executable file.
```suggestion
Let's consider the case when we are in a terminal (bash) and we launch an executable file.
```

2023-07-17 08:24 UTC, teodutu commented on application-lifetime/index.md
> +- a rule tu craete the `main.o` object file - the code of our application
```suggestion
- a rule to create the `main.o` object file - the code of our application
```

2023-07-17 08:24 UTC, teodutu commented on application-lifetime/index.md
> +- two rules to create the static library **libhello**
```suggestion
- two rules to create the static library `libhello.a`
```

2023-07-17 08:38 UTC, mariasfiraiala requested changes
I'd like to have this merged as soon as possible. It looks fine to me, might be a bit terse from time to time, but it will do. As @teodutu said, we'll make it better, if needed, for the next season.

After applying @teodutu's suggestions, @cristian-vijelie, please, take care of the linter issues and let's have it upstream!

2023-07-18 03:49 UTC, teodutu requested changes
Now it looks better. Just 2 more things to consider before fixing the linter failures and merging this:
- Ditch the copyright messages. For one, they say 2021 instead of 2023 and seem rather pedantic to me.
- Remove the TOC at the beginning.

2023-07-18 03:49 UTC, teodutu commented on application-lifetime/index.md
>  ## Table of Contents
You still haven't deleted it.

2023-07-18 04:55 UTC, cristian-vijelie commented on application-lifetime/index.md
>  ## Table of Contents
it is deleted. Look at the whole file

2023-07-18 04:56 UTC, cristian-vijelie commented
Regarding the linter errors:
* No copyright message will generate an error
* checkpatch complains about spaces being used instead of tabs. If I change the spaces to tabs, superlinter will complain
* superlinter complains that one '{' is on the next line; afaik, brackets for functions should be placed on the next line
* checkpatch complains that there is a space before an endline, in the delimiters given to strtok
* superlinter complains that there is no top-of-the-document section (no section with #), which I don't know how to solve

2023-07-18 05:58 UTC, teodutu commented
> Regarding the linter errors:
> 
>     * No copyright message will generate an error

This is so dumb. We need to disable this. Which linter is causing this?

>     * checkpatch complains about spaces being used instead of tabs. If I change the spaces to tabs, superlinter will complain

Fuck... we need to copy the superlinter config from the OS repo. I'll do that in just a bit.

>     * superlinter complains that one '{' is on the next line; afaik, brackets for functions should be placed on the next line

Same: I'll copy the superlinter configs here.

>     * checkpatch complains that there is a space before an endline, in the delimiters given to strtok

![image](https://github.com/security-summer-school/essentials/assets/19818392/26aea426-b1d1-4336-868c-4ba845af511a)

>     * superlinter complains that there is no top-of-the-document section (no section with #), which I don't know how to solve

Just change the first heading to `#`.

2023-07-18 06:17 UTC, razvand approved these changes

2023-07-18 06:18 UTC, merged