Add `Binary analysis` session content
security-summer-school/essentials pull request #37
Opened 2023-07-16 12:34 UTC by cristian-vijelie

2023-07-16 14:36 UTC, mariasfiraiala requested changes
Thanks @cristian-vijelie. You'll find my suggestions below.

2023-07-16 14:36 UTC, mariasfiraiala commented on binary-analysis/index.md
> +Static analysis means investigating the binary without running it.
```suggestion
Static analysis implies investigating the binary without running it.
```

2023-07-16 14:36 UTC, mariasfiraiala commented on binary-analysis/index.md
> +But it should be used before any investigation, to make sure that the binary is a binary file, and not an archive.
```suggestion
It should be used before any investigation, to make sure that the binary is indeed a binary file, and not an archive.
```

2023-07-16 14:36 UTC, mariasfiraiala commented on binary-analysis/index.md
> +That's why they are almost used first when analysing a binary.
```suggestion
That's why they are, almost always, used first when analysing a binary.
```

2023-07-16 14:36 UTC, mariasfiraiala commented on binary-analysis/index.md
> +It also shows where those symbols are placed: text (T or t), rodata (R or r), bss (B or b), etc.
```suggestion
It also shows where these symbols are placed: text (T or t), rodata (R or r), bss (B or b), etc.
```

2023-07-16 14:36 UTC, mariasfiraiala commented on binary-analysis/index.md
> +Capital-letter symbols are global, meaning they can be refferenced from another object files.
```suggestion
Capital-letter symbols are global, meaning they can be referenced from other object files.
```

2023-07-16 14:36 UTC, mariasfiraiala commented on binary-analysis/index.md
> +`objdump` is pretty good at what is must do.
```suggestion
`objdump` is pretty good at what it must do.
```

2023-07-16 14:36 UTC, mariasfiraiala commented on binary-analysis/index.md
> +`Ghidra` is a decompiler: it turns a binary file into C code.
```suggestion
`Ghidra` is a decompiler: it turns a binary file back into C code.
```

2023-07-16 14:36 UTC, mariasfiraiala commented on binary-analysis/index.md
> +Dynamic analysis means observing the behaviour of the binary, when it it running.
```suggestion
Dynamic analysis means observing the behaviour of the binary, while it is running.
```

2023-07-16 14:36 UTC, mariasfiraiala commented on binary-analysis/index.md
> +Generally, the the context (registers, stack, variables) is also displayed.
```suggestion
Generally, the context (registers, stack, variables) is also displayed.
```

2023-07-16 14:36 UTC, mariasfiraiala commented on binary-analysis/index.md
> +Today we use only tracing.
```suggestion
Today, we are going to explore tracing.
```

2023-07-17 09:57 UTC, teodutu commented on binary-analysis/index.md
> +For `strings` and `file` there is no counter-measure to hide the data that would be found by them.
Binary obfuscation and encryption may be used to protect against `strings`. Stripping also helps a little bit because the names of the symbols are no longer visible.

2023-07-18 08:15 UTC, gabrielmocanu submitted a review, later dismissed

2023-07-19 20:04 UTC, mariasfiraiala requested changes
Thanks @cristian-vijelie. See the few comments from me below.

2023-07-19 20:04 UTC, mariasfiraiala commented on binary-analysis/index.md
> +`objdump` is a dissassembler.
```suggestion
`objdump` is a disassembler.
```

2023-07-19 20:04 UTC, mariasfiraiala commented on binary-analysis/index.md
> +It becomes less helpful if the binary is large, with multiple functions that call eachother and we have a hard time understanding the flow of the application.
```suggestion
It becomes less helpful if the binary is large, with multiple functions that call each other and we have a hard time understanding the flow of the application.
```

2023-07-19 20:04 UTC, mariasfiraiala commented on binary-analysis/index.md
> +Sandboxing is a more complex process, in which you isolate a binary in a virtual machine (usually), run it and observer the changes made on the system: modified files, network traffic, etc.
```suggestion
Sandboxing is a more complex process, in which you isolate a binary in a virtual machine (usually), run it and observe the changes made on the system: modified files, network traffic, etc.
```

2023-07-20 06:53 UTC, mariasfiraiala approved these changes
Looks good to me now, thanks!

2023-07-20 07:04 UTC, merged